version: "3.12"

services:
  web:
    image: web:1.0
    restart: always
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    env_file:
      - ./.env.prod
    networks:
      - app_task_manage_network

  api:
    image: tasksmanager_api:1.0
    restart: always
    build:
      context: ./Backend
      dockerfile: Dockerfile.prod
    command: gunicorn Backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - tmapp_static_volume:/home/app/api/static
      - tmapp_media_volume:/home/app/api/media
      - tmapp_wheels_volume:/usr/src/api/wheels
    ports:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    ports:
      - 5434:5432
    volumes:
      - tmapp_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - app_task_manage_network

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - tmapp_static_volume:/home/app/api/static
      - tmapp_media_volume:/home/app/api/media
    ports:
      - 1337:80
    depends_on:
      - api
      - web
    networks:
      - app_task_manage_network

volumes:
  tmapp_postgres_data:
  tmapp_static_volume:
  tmapp_media_volume:
  tmapp_wheels_volume:

networks:
  app_task_manage_network:
    name: app_task_manage_network
    external: false
