version: "3.12"

services:
  # web:
  #   build:
  #     context: ./Frontend
  #     dockerfile: Dockerfile
  #   command: gunicorn Backend.wsgi:application --bind
  api:
    image: tasksmanager_api:1.0
    build:
      context: ./Backend
      dockerfile: Dockerfile.prod
    command: gunicorn Backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/api/staticfiles
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
